compile: driver.c gram_module.h gram_module.c parse.c read_grammar.c
	gcc -o prog driver.c gram_module.h gram_module.c parse.c read_grammar.c -g
	echo Compiled file with name 'prog'. Kindly run that file 
